import Head from 'next/head'
import { Inter } from 'next/font/google'

import { Container } from 'react-bootstrap'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import Feature from '@/components/Feature'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Section Navbar */}
        <Navbar></Navbar>

        <Container >
          {/* Section Hero */}
          <Hero></Hero>
          
          {/* Section Feature */}
          <Feature></Feature>
        </Container>
      </main>
    </>
  )
}
