// src/layouts/MainLayout.js
import Head from 'next/head';
import React from 'react';
import Navbar from '@/components/Navbar'
import { Container } from 'react-bootstrap';

const Layout = ({ children }) => {
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Container>
            {children}
        </Container>
      </main>
    </>
  );
};

export default Layout;
