import Head from "next/head";
import Navbar from "@/components/Navbar";
import LayoutContext from "@/context/LayoutContext";
import { useEffect, useState } from "react";
import { getCookie } from "@/utils/cookies";

export default function Layout({ children }) {
  const [userData, setUserData] = useState({});
  const [isLogin, setIsLogin] = useState(false);

  useEffect(() => {
    const userDataCookie = getCookie("userData");
    if (userDataCookie) {
      setUserData(JSON.parse(userDataCookie));
      setIsLogin(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LayoutContext.Provider
          value={{ userData, setUserData, isLogin, setIsLogin }}
        >
          {/* Section Navbar */}
          <Navbar></Navbar>
          {children}
        </LayoutContext.Provider>
      </main>
    </>
  );
}
