import Head from "next/head";
import Navbar from "@/components/Navbar";
import GlobalContext from "@/contexts/GlobalContext";
import { useEffect, useState } from "react";
import { getCookie } from "@/utils/cookies";

export default function Layout({ children }) {

  const [isLogin, setIsLogin] = useState(false);
  const [userData, setUserData] = useState({});

  useEffect(() => {
    const userDataCookie = getCookie("userData");
    if (userDataCookie) {
      setUserData(userDataCookie);
      setIsLogin(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GlobalContext.Provider value={{isLogin, setIsLogin, userData, setUserData}} >
          {/* Section Navbar */}
          <Navbar></Navbar>
          {children}
        </GlobalContext.Provider>
      </main>
    </>
  );
}
